### ISSUE TITLE
network policy always blocks 10.0.0.0/8

### ISSUE THREAD

**Issue by sloppycoder** [sloppycoder/k3s-fluxcd-vinolab#3]
the default network policy contains the following
```
---
# 5. allow egress to hosts external to the cluster
# the address ranges in except list depends on the cluster
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cluster-external
spec:
  podSelector: {}
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8

```

but the except ```10.0.0.0/8``` is arbitary, and it should depend on the way cluster is setup.

when deployed on an EC2 Debian VM, the external RDS has the IP address of ```10.0.29.28```, and is blocked by this policy.

**Comment by sloppycoder** [comment]
when deploying postgres database using cnpg, some pod tried to access k8s API at 10.43.0.1, which was also blocked by this rule. 

workaround is added explicit rule before this blocking rule. see [this commit](https://github.com/sloppycoder/k3s-fluxcd-vinolab/blob/e1435e8243420199ec94ec7f2711cc533321cd49/infra/configs/namespaces/test/network-policy.yaml)

```yaml
---
# 5. allow egress to K8S api server
# the cidr range is broad, hopefully it works in most setups
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-k8s-api-egress
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32
      ports:
        - protocol: TCP
          port: 443

```

the problem is though, the k8s api can differ from installations. this makes this configuration non portable!!

Perhaps the solution is to use DNS aware CNI like Cillium? some serious re-thinking is needed in this area.
